site_name: dadi
repo_url: https://github.com/RyanGutenkunst/dadi
edit_uri: ""
docs_dir: 'doc'
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
plugins:
  - search
  - mkdocs-autoapi:
      # autoapi_dir: dadi
      autoapi_ignore: [LICSENSE, __init__.py, dadi/.*, dadi/*/.*, dadi/__init__.py, dadi/*/__init__.py]
      autoapi_file_patterns:
        - "dadi/*.py"
        - "dadi/*/*.py"
      autoapi_add_nav_entry: API
  - mkdocstrings
      # default_handler: python
      # handlers:
      #   python:
      #     paths: [src]
nav:
- Home: 'index.md'
- User Guide:
        - 'Installation': 'user-guide/installation.md'
        - 'Importing data': 'user-guide/importing-data.md'
        - 'Manipulating spectra': 'user-guide/manipulating-spectra.md'
        - 'Specifying a model': 'user-guide/specifying-a-model.md'
        - 'Simulation and fitting': 'user-guide/simulation-and-fitting.md'
        - 'Plotting': 'user-guide/plotting.md'
        - 'Bootstrapping': 'user-guide/bootstrapping.md'
        - 'Uncertainty analysis': 'user-guide/uncertainty-analysis.md'
        - 'Likelihood ratio test': 'user-guide/likelihood-ratio-test.md'
        - 'Triallelic spectra': 'user-guide/triallelic-spectra.md'
        - 'DFE inference': 'user-guide/dfe-inference.md'
        - 'Inbreeding': 'user-guide/inbreeding.md'
        - 'Low-Pass': 'user-guide/low-pass.md'
        - 'Polyploid subgenomes': 'user-guide/polyploid-subgenomes.md'
        - 'GPU computing': 'user-guide/GPU-computing.md'
        - 'Demes integration': 'user-guide/demes.md'
        - 'Frequently asked questions': 'user-guide/frequently-asked-questions.md'
        - 'References': 'user-guide/references.md'
- Examples:
        - 'Frequency spectrum from data': 'examples/fs_from_data/fs_from_data.md'
        - 'Demography inference for YRI and CEU': 'examples/YRI_CEU/YRI_CEU.md'
        - 'DFE inference': 'examples/DFE/DFE.md'
        - 'Triallelic model': 'examples/Triallele/TrialleleModel.md'
        - 'Two Locus model': 'examples/TwoLocus/TwoLocusModel.md'
        - 'Basic Workflow 1D Demographics' : 'examples/basic_workflow/basic_workflow_1d_demographics.md'
        - 'Basic Workflow 2D Demographics' : 'examples/basic_workflow/basic_workflow_2d_demographics.md'
        - 'Basic Workflow Cache Generation' : 'examples/basic_workflow/basic_workflow_cache_generation.md'
        - 'Basic Workflow 1D DFE' : 'examples/basic_workflow/basic_workflow_1d_dfe.md'
        - 'Basic Workflow 2D DFE' : 'examples/basic_workflow/basic_workflow_2d_dfe.md'
        - 'Low-Pass Example' : 'examples/LowPass/low-pass.md'
# - API: autoapi/
# - API: 'api/dadi/index.html'
